{% set name = "hs-process" %}
{% set version = "0.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/c3/bb/c26c92a0671f9d98434fae8a9491ff60e5628763da0a8b552d0c27188f71/hs_process-0.0.4.tar.gz"
  sha256: a28e71a82e2f52eb082382d3dc43f04e694cdd556ad91b104a9f0069d8d5ecb9

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python >=3.6

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - geopandas
    - python >=3.6
    - seaborn
    - spectral
    - tqdm
    - findiff

test:
  imports:
    - hs_process

about:
  home: "https://github.com/tnigon/hs_process"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "An open-source Python package for geospatial processing of aerial hyperspectral imagery"
  doc_url: https://hs-process.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/tnigon/hs_process

extra:
  recipe-maintainers:
    - tnigon
